version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: go_simple_website
    environment:
      NODE_ID: 'development'
      PORT: '8080'
    ports:
      - 8080:8080
